version: '2.1'

services:
  sl4a:
    build: .
    image: sl4a
    container_name: sl4a
    volumes:
      - "data_work:/home/ubuntu/work"
    restart: always
    ports:
      - "22:22"
      - "5555:5555"
      - "5554:5554"
      - "5037:5037"
    network_mode: "host"

volumes:
  data_work: